apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: account-service
  app.kubernetes.io/instance: account-service-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: account-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=mkit.service.account
      # - MICRO_SERVER_ADVERTISE="$(ACCOUNT_SERVICE_ENDPOINT):8080"
      - DATABASE_HOST=$(DATABASE_ENDPOINT)

vars:
  - name: ACCOUNT_SERVICE_ENDPOINT
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
