version: "3.7"

services:
  envoy:
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c etc/envoy/envoy.yaml
    volumes:
      - "./config/base/envoy/envoy.yaml:/etc/envoy/envoy.yaml"
    expose:
      - "9090"
      - "9901"
    ports:
      - "9090:9090"
      - "9901:9901"
