---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          resources:
            requests:
              cpu: 250m
              memory: 1G
            limits:
              cpu: 500m
              memory: 2G
