---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
  labels:
    app.kubernetes.io/name: etcd-operator
spec:
  group: etcd.database.coreos.com
  scope: Namespaced
  version: v1beta2
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    singular: etcdcluster
    plural: etcdclusters
    shortNames:
      - etcd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator
  namespace: key-dev
  labels:
    app.kubernetes.io/name: etcd-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: etcd-operator
  namespace: key-dev
  labels:
    app.kubernetes.io/name: etcd-operator
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdclusters
      - etcdbackups
      - etcdrestores
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: etcd-operator
  namespace: key-dev
  labels:
    app.kubernetes.io/name: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-operator
subjects:
  - kind: ServiceAccount
    name: etcd-operator
    namespace: key-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: key-dev
  labels:
    app.kubernetes.io/name: etcd-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd-operator
    spec:
      serviceAccountName: etcd-operator
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: etcd-operator
          image: "xmlking/etcd-operator:v0.10.1"
          # image: "quay.io/coreos/etcd-operator:v0.9.4"
          command:
            - etcd-operator
            # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
            # - -cluster-wide
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
