apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
  labels:
    app.kubernetes.io/name: etcd-operator
spec:
  group: etcd.database.coreos.com
  scope: Namespaced
  version: v1beta2
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    singular: etcdcluster
    plural: etcdclusters
    shortNames:
      - etcd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator
  namespace: default
  labels:
    app.kubernetes.io/name: etcd-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: etcd-operator
  namespace: default
  labels:
    app.kubernetes.io/name: etcd-operator
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdclusters
      - etcdbackups
      - etcdrestores
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: etcd-operator
  namespace: default
  labels:
    app.kubernetes.io/name: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-operator
subjects:
  - kind: ServiceAccount
    name: etcd-operator
    namespace: default
---

