apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account
  - emailer
  - greeter
  - recorder

configMapGenerator:
#  - name: env-vars
#    behavior: merge
  - name: env-vars-common
    literals:
      - APP_ENV=development
      - MICRO_LOG_LEVEL=debug
      - MICRO_CLIENT_REQUEST_TIMEOUT=5s

#secretGenerator:
#   - name: app-tls
#     files:
#       - secret/tls.cert
#       - secret/tls.key
