commonLabels:
  app.kubernetes.io/name: nats
  app.kubernetes.io/instance: nats-abcxzy
  app.kubernetes.io/component: infra

resources:
  - nats.yaml

vars:
  - name: NATS_SERVICE_ENDPOINT
    objref:
      kind: Service
      name: nats
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
