apiVersion: "etcd.database.coreos.com/v1beta2"
kind: EtcdCluster
metadata:
  name: etcd-cluster
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "v3.3.18"
  repository: "quay.io/coreos/etcd"
  pod:
    labels:
      app.kubernetes.io/name: etcd-cluster
    busyboxImage: "busybox:1.28.0-glibc"
    tmpfs: true
    HostNetwork: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
