apiVersion: v1
kind: Service
metadata:
  name: service-headless
spec:
  clusterIP: None
  # We want the servers to become available even if they're not ready
  publishNotReadyAddresses: true
  ports:
    - name: grpc-port
      appProtocol: grpc
      port: 8080
      protocol: TCP
      targetPort: grpc-port
